#!/usr/bin/env bash

FILES=$(find . -name "*.py" -type f);

# read and loop through the FILES string.
while IFS=' ' read -ra ADDR;
do
	for file in "${ADDR[@]}"; do
		# process "$file"
		pycodestyle --first "$file";
	done;
done <<< "$FILES";
